name: Aula Pratica 5 CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up environment
      shell: bash
      run: |
        if [[ $RUNNER_OS == "Linux" ]]; then
          sudo apt-get update
          sudo apt-get install g++ -y
        elif [[ $RUNNER_OS == "macOS" ]]; then
          brew install gcc
        elif [[ $RUNNER_OS == "Windows" ]]; then
          choco install mingw
        fi

    - name: Compile and Run Tests
      shell: bash
      run: |
        if [[ $RUNNER_OS == "Windows" ]]; then
          g++ car_rental.cpp client.cpp flight.cpp hotel.cpp integration_tests.cpp trip.cpp unit_tests.cpp main.cpp -o TravelAgency.exe
          ./TravelAgency.exe
        else
          g++ car_rental.cpp client.cpp flight.cpp hotel.cpp integration_tests.cpp trip.cpp unit_tests.cpp main.cpp -o TravelAgency
          ./TravelAgency
        fi